version: "3"
services:     
  humanscape-backend:
    container_name: humanscape-backend
    build: 
      context: .
      dockerfile: ./Dockerfile-deploy
    restart: always 
    environment: 
      DJANGO_SETTINGS_MODULE: humanscape.settings.deploy
    command: 
      - bash 
      - -c 
      - | 
        python manage.py migrate
        echo yes | python manage.py collectstatic
        python manage.py crontab remove
        python manage.py crontab add
        gunicorn humanscape.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app/ 

  humanscape-nginx: 
    image: nginx 
    container_name: humanscape-nginx
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "8000:8000" 
    environment:
      - TZ="Asia/Seoul"
    depends_on:
      - humanscape-backend